#!/usr/bin/env bash

set -e

# Sort imports one per line, so autoflake can remove unused imports
isort --recursive  --force-single-line-imports botx_fsm tests example

autoflake --recursive --remove-all-unused-imports --remove-unused-variables --in-place botx_fsm tests example --exclude=__init__.py
black botx_fsm tests example
isort --recursive botx_fsm tests example
