name: Python application
on: push
jobs:

  test:
    name: Test
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: [ "3.8", "3.9", "3.10", "3.11", "3.12" ]

    steps:
      - name: Setup dependencies
        uses: ExpressApp/github-actions-poetry@v0.4
        with:
          python-version: ${{ matrix.python-version }}
          poetry-version: "1.3.2"

      - name: Run tests
        run: |
          poetry run ./scripts/test


  lint:
    name: Lint
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: [ "3.8", "3.9", "3.10", "3.11", "3.12" ]

    steps:
      - name: Setup dependencies
        uses: ExpressApp/github-actions-poetry@v0.4
        with:
          python-version: ${{ matrix.python-version }}
          poetry-version: "1.3.2"

      - name: Run lint
        run: |
          poetry run ./scripts/lint
  

  docs-lint:
    name: Docs lint
    runs-on: ubuntu-22.04

    steps:
      - name: Setup dependencies
        uses: ExpressApp/github-actions-poetry@v0.4
        with:
          poetry-version: "1.3.2"

      - name: Run linters
        run: |
          poetry run ./scripts/docs-lint
